{
 "title": "PACSLTK Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cold starts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(counter_invoker_containerStart_cold_counter_total[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Docker rm",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(histogram_invoker_docker_rm_finish_seconds_count[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(histogram_http_post_counter_seconds_count[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Cold Start Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(counter_invoker_containerStart_cold_counter_total[${__range_s}s])) / sum(increase(histogram_http_post_counter_seconds_count[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "pacs_container_count", "legendFormat": "{{tag}}" }
   ]
  },
  {
   "title": "Docker rm and run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(histogram_invoker_docker_rm_finish_seconds_count[10s]) / 2",
     "legendFormat": "Kill"
    },
    {
     "expr": "increase(histogram_invoker_docker_run_finish_seconds_count[10s]) / 2",
     "legendFormat": "Run"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pacs_container_count", "legendFormat": "{{tag}}" }
   ]
  },
  {
   "title": "Average Blocking Activation Time [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(histogram_invoker_activationRun_finish_seconds_sum[$interval]) / increase(histogram_invoker_activationRun_finish_seconds_count[$interval])",
     "legendFormat": "Activation Run Finish"
    },
    {
     "expr": "increase(histogram_http_post_counter_seconds_sum[$interval]) / increase(histogram_http_post_counter_seconds_count[$interval])",
     "legendFormat": "Activation Finish"
    }
   ]
  },
  {
   "title": "Cold Starts - Killed Containers [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(counter_invoker_containerStart_cold_counter_total[20s]) * 15 / 20",
     "legendFormat": "Cold Starts"
    },
    {
     "expr": "idelta(pacs_container_count[10s])",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Activations [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(openwhisk_statsd_controller0_counter_loadbalancer_activations_counter[$interval]))"
    }
   ]
  },
  {
   "title": "Blocking Activation Finish",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openwhisk_statsd_controller0_histogram_controller_blockingActivation_finish{quantile=\"0.5\"}",
     "legendFormat": "Percentile 50"
    },
    {
     "expr": "openwhisk_statsd_controller0_histogram_controller_blockingActivation_finish{quantile=\"0.9\"}",
     "legendFormat": "Percentile 90"
    },
    {
     "expr": "openwhisk_statsd_controller0_histogram_controller_blockingActivation_finish{quantile=\"0.99\"}",
     "legendFormat": "Percentile 99"
    }
   ]
  },
  {
   "title": "RT LE [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(histogram_http_post_counter_seconds_bucket[$interval])) by (le)",
     "legendFormat": "RT < {{le}}"
    }
   ]
  }
 ]
}